### ISSUE TITLE
Want to try ,but couldnt manage

### ISSUE THREAD

**Issue by ousturali** [EvotecIT/Testimo#101]
hi ,
i want to try your code ,in a windows 2012R2 dc, but couldnt manage,
i tried to install with (Install-Module -Name Testimo -AllowClobber -Force) 
but it gave me errror (dependecy for nuget )

then i tried to install it with (Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force)
also it didnt worked,

Can you advise anything else (i thnik i manually insall nuget on my dc )

**Comment by PrzemyslawKlys** [comment]
Make sure you have PowerShell 5.1

```
Install-Module PowerShellGet -Force
```

let it update/restart Powershell and try again.

**Comment by ousturali** [comment]
unfortunately it didnt help.It gave the error

WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Install-PackageProvider : No match was found for the specified search criteria for the provider
'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package
has the tags.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7405 char:21
+ ...     $null = PackageManagement\Install-PackageProvider -Name $script:N ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-Pac
   kageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackagePro
   vider

PackageManagement\Import-PackageProvider : No match was found for the specified search criteria and provider name
'NuGet'. Try 'Get-PackageProvider -ListAvailable' to see if the provider exists on the system.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7411 char:21
+ ...     $null = PackageManagement\Import-PackageProvider -Name $script:Nu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (NuGet:String) [Import-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.ImportPackageProv
   ider

WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Get-PackageProvider : Unable to find package provider 'NuGet'. It may not be imported yet. Try
'Get-PackageProvider -ListAvailable'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7415 char:30
+ ... tProvider = PackageManagement\Get-PackageProvider -Name $script:NuGet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...PackageProvider:GetPackageProvider) [Get-PackageProvi
   der], Exception
    + FullyQualifiedErrorId : UnknownProviderFromActivatedList,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPacka
   geProvider

Install-Module : NuGet provider is required to interact with NuGet-based repositories. Please ensure that '2.8.5.201'
or newer version of NuGet provider is installed.
At line:1 char:1
+ Install-Module PowerShellGet -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Module], InvalidOperationException
    + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Install-Module

**Comment by PrzemyslawKlys** [comment]
Stupid question. DO you have the internet? `Get-PSRepository` what does that show?

**Comment by ousturali** [comment]
yes ,i have internet

output is


PS C:\Users\Administrator> Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2

**Comment by PrzemyslawKlys** [comment]
can you reach that gallery from that PC?

**Comment by ousturali** [comment]
Yes  i can ,when i try from the browser 
an xml page welcomes

**Comment by PrzemyslawKlys** [comment]
Try this one: https://evotec.xyz/powershellgallery-disables-support-for-tls-1-0-breaking-install-module/

**Comment by ousturali** [comment]
Hi again
I had installed a new windos10 machine,and RSAT as you had mentioned. Then i can successfully tested your wonderful script.Thank you very much.
I appreciate your work.
great job.
