### ISSUE TITLE
NetSessionEnumeration not run against target

### ISSUE THREAD

**Issue by decopaper** [EvotecIT/Testimo#102]
The "Get-PSRegistry" command in NetSessionEnumeration.ps1 (line 6) does not specify "ComputerName", so the test is run against the local computer and not the target domain controller:

`$Registry = Get-PSRegistry -RegistryPath "HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\DefaultSecurity"`

**Comment by PrzemyslawKlys** [comment]
Tnx for reporting. Silly mistake. New release is out with a fix for this.
