### ISSUE TITLE
0.0.45 is the latest available from PSGallery

### ISSUE THREAD

**Issue by Sparticuz** [EvotecIT/Testimo#112]
`[i][Testimo] Version [Informative] [Current: 0.0.45, Published: 0.0.46 at 10/29/2020 15:29:18. Update?]`

I just installed it today for the first time.

**Comment by PrzemyslawKlys** [comment]
Testimo checks for the current version on GitHub. Usually, there would be the same version on PSGallery as on GitHub with second difference. But once it was posted to PSGallery - they reverted PSGallery from backup and 0.0.46 was lost on PSGallery. I need to post 0.0.47 for things to resolve. Sorry for this. I need to finish playing with GPOZaurr, then make sure to reflect changes in Testimo and then I will be updating Testimo on more frequent basis.
