### ISSUE TITLE
0.47 doesn't run

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#115]
[2] [10:53] C:\Scripts > invoke-testimo
[i][Testimo] Version [Informative] [Current/Latest: 0.0.47 at 01/19/2021 03:05:50]
[i][Testimo] Using configuration defaults [Informative] [No configuration provided by user]
[i][Forest] Forest [Informative]

   [i][hidden.com] Domain hidden.com [Informative]
   [i][hidden.com] Domain hidden.com [Time to execute tests: 0 days, 0 hours, 0 minutes, 0 seconds, 28 milliseconds][Tests Total: 0, Passed: 0, Failed: 0, Skipped: 0]
[i][Forest] Forest [Time to execute tests: 0 days, 0 hours, 0 minutes, 0 seconds, 89 milliseconds][Tests Total: 0, Passed: 0, Failed: 0, Skipped: 0]

**Comment by PrzemyslawKlys** [comment]
Sorry for that. It works per given test - just doesn't work for all tests.

**Comment by PrzemyslawKlys** [comment]
Fixed
