### ISSUE TITLE
Error when running invoke-testimo

### ISSUE THREAD

**Issue by dkervin** [EvotecIT/Testimo#116]
When I run this command I receive the following error:
Start-Testing : Cannot process argument transformation on parameter 'ExtendedValue'. Cannot convert value to type System.String.
At C:\Program Files\WindowsPowerShell\Modules\Testimo\0.0.48\Testimo.psm1:4939 char:13
+     $null = Start-Testing -Scope 'Forest' -ForestInformation $ForestD ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-Testing], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Start-Testing

Thoughts?

**Comment by PrzemyslawKlys** [comment]
Which version?

**Comment by dkervin** [comment]
[Current: 0.0.48]


Dennis Ervin
Senior Systems Engineer
Seaboard Foods
9000 W. 67th Street
Merriam, KS 66202
(913) 676-8907
Dennis.ervin@seaboardfoods.com<mailto:Dennis.ervin@seaboardfoods.com>
Dennis.ervin@seaboardfoods.us<mailto:Dennis.ervin@seaboardfoods.us> (Skype)

**Comment by PrzemyslawKlys** [comment]
What did you run to execute it?

**Comment by dkervin** [comment]
Simly ran invoke-testimo with no parameters.

**Comment by PrzemyslawKlys** [comment]
Any specific test it failed on?

**Comment by dkervin** [comment]
As noted in my first message, it errors on line 4939 of testimo.psm1 when it tries to run the start-testing command.

**Comment by PrzemyslawKlys** [comment]
Ye, I was more interested which Testimo test failed

![image](https://user-images.githubusercontent.com/15063294/105719839-0ce8a780-5f23-11eb-8900-6b4e3521d003.png)

In this case it seems it failed on Time Synchronization. I'll fix it today - I've been reworking Testimo in last few versions and broke it in the process. sorry for that

**Comment by dkervin** [comment]
Mine is a bit different;
Cannot process argument transformation on parameter 'ExtendedValue'. Cannot convert value to type System.String.

Same issue?

**Comment by PrzemyslawKlys** [comment]
Should be, i'll fix both

**Comment by dkervin** [comment]
Great, thank you!

**Comment by PrzemyslawKlys** [comment]
New version is released. Please update and try again. Please be aware that running Invoke-Testimo without picking tests you need will work but HTML report will be very slow when switching tabs or scrolling. I've to resolve this issue, but for now it is what it is. This is because each tab has lots of tables that are refreshed on tabs switch.

**Comment by dkervin** [comment]
OK, I will keep that in mind.

Thanks for your assistance.

Dennis Ervin
Senior Systems Engineer
Seaboard Foods
9000 W. 67th Street
Merriam, KS 66202
(913) 676-8907
Dennis.ervin@seaboardfoods.com<mailto:Dennis.ervin@seaboardfoods.com>
Dennis.ervin@seaboardfoods.us<mailto:Dennis.ervin@seaboardfoods.us> (Skype)

**Comment by AJDurant** [comment]
I've got the same issue on 0.0.49, at a different point
```
Invoke-Testimo
[i][Testimo] Version [Informative] [Current/Latest: 0.0.49 at 01/25/2021 16:16:52]
[i][Testimo] Using configuration defaults [Informative] [No configuration provided by user]
...
Aging primary DNS Zone [Informative]
Start-Testing : Cannot process argument transformation on parameter 'ExtendedValue'. Cannot convert value to type System.String.
At C:\Program Files\WindowsPowerShell\Modules\Testimo\0.0.49\Testimo.psm1:5102 char:17
+ ...             Start-Testing -Scope 'Domain' -Domain $Domain -DomainInfo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-Testing], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Start-Testing
```

**Comment by PrzemyslawKlys** [comment]
If you run it like that? Does it work?

```powershell
invoke-testimo -Sources DomainDnsZonesAging -ShowReport
```

**Comment by PrzemyslawKlys** [comment]
OK, I think i found the reason. If the cmdlet would give more than 1 error it would fail because it expected one string output when it was given an array of strings. Please update and test again.

**Comment by dkervin** [comment]
Still seeing the error, just in a different location. I have updated testimo before testing again. This time the error occurred at line 4950.

Dennis Ervin
Senior Systems Engineer
Seaboard Foods
9000 W. 67th Street
Merriam, KS 66202
(913) 676-8907
Dennis.ervin@seaboardfoods.com<mailto:Dennis.ervin@seaboardfoods.com>
Dennis.ervin@seaboardfoods.us<mailto:Dennis.ervin@seaboardfoods.us> (Skype)

**Comment by PrzemyslawKlys** [comment]
You need to provide more data - just line numbers is not enough. Which test, what error message

**Comment by PrzemyslawKlys** [comment]
Did you do 

```
Install-Module Testimo -Force
Import-Module Testimo -Force
```

https://i.imgur.com/JaC1yq1.png

The line number is very unlikely to give error.

**Comment by AJDurant** [comment]
```
invoke-testimo -Sources DomainDnsZonesAging -ShowReport
[i][Testimo] Version [Informative] [Current: 0.0.49, Published: 0.0.50 at 01/25/2021 18:04:54. Update?]
[i][Testimo] Using configuration defaults [Informative] [No configuration provided by user]
[i][Forest] Forest [Informative]

   [i][ad.XXXXXX.com] Domain ad.XXXXXX.com [Informative]
      [i][ad.XXXXXX.com] Aging primary DNS Zone [Informative]
Start-Testing : Cannot process argument transformation on parameter 'ExtendedValue'. Cannot convert value to type System.String.
At C:\Program Files\WindowsPowerShell\Modules\Testimo\0.0.49\Testimo.psm1:5102 char:17
+ ...             Start-Testing -Scope 'Domain' -Domain $Domain -DomainInfo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-Testing], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Start-Testing
```

```
invoke-testimo -Sources DomainDnsZonesAging -ShowReport
[i][Testimo] Version [Informative] [Current/Latest: 0.0.50 at 01/25/2021 18:04:54]
[i][Testimo] Using configuration defaults [Informative] [No configuration provided by user]
[i][Forest] Forest [Informative]

   [i][ad.XXXXXX.com] Domain ad.XXXXXX.com [Informative]
      [i][ad.XXXXXX.com] Aging primary DNS Zone [Informative]
         [t][ad.XXXXXX.com] Aging primary DNS Zone [Fail] [Failed to get the zone information for ad.XXXXXX.com on server dc00.ad.XXXXXX.com.; Failed to get the zone information for ad.XXXXXX.com on server dc01.ad.XXXXXX.com.]
         [t][ad.XXXXXX.com] Zone DNS aging should be identical on all DCs [Fail] [Input data not provided. Failing test.]
      [i][ad.XXXXXX.com] Aging primary DNS Zone [Time to execute tests: 0 days, 0 hours, 0 minutes, 5 seconds, 271 milliseconds][Tests Total: 2, Passed: 0, Failed: 2, Skipped: 0]
   [i][ad.XXXXXX.com] Domain ad.XXXXXX.com [Time to execute tests: 0 days, 0 hours, 0 minutes, 5 seconds, 578 milliseconds][Tests Total: 2, Passed: 0, Failed: 2, Skipped: 0]
[i][Forest] Forest [Time to execute tests: 0 days, 0 hours, 0 minutes, 5 seconds, 671 milliseconds][Tests Total: 2, Passed: 0, Failed: 2, Skipped: 0]
```

So that bit seems to be fixed, thanks!

**Comment by PrzemyslawKlys** [comment]
Cool! Thank you.

**Comment by saliumaama** [comment]
I'm having this error message when I run Invoke-Testimo. Not sure why. Is there anything I'm doing wrong ? Is Testimo supposed to be run ONLY on domain controllers ?

[i][Testimo] Version [Informative] [Current: 0.0.72]
[i][Testimo] Using configuration defaults [Informative] [No configuration provided by user]
Get-WinADForestDetails : Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Testimo\0.0.72\Testimo.psm1:6298 char:22
+ ... stDetails = Get-WinADForestDetails -WarningVariable ForestWarning -Wa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-WinADForestDetails], RuntimeException
    + FullyQualifiedErrorId : NullArray,Get-WinADForestDetails

![image](https://user-images.githubusercontent.com/91435738/134823666-a68eca48-286b-4d09-9f81-fdb819f6ef9a.png)

**Comment by PrzemyslawKlys** [comment]
I would suggest opening a new issue. You can run it on Windows 10 without any issue. Most likely something is different on your domain that makes it unique, and something that I don't expected to find.

Please check: Get-ADForest, Get-ADDomain - does that work properly?

**Comment by saliumaama** [comment]
I open new issue already.

That screenshot I sent was sent Windows 10. I have RSAT installed on it.

Do you have to specify the domain name after Invoke-teatimo command ?
