### ISSUE TITLE
Misspelled word in report (Extream -> Extreme)

### ISSUE THREAD

**Issue by mojomojoman** [EvotecIT/Testimo#120]
I know a github bug report isn't the place for this but I have to start by saying WOW. What a fantastic module this is.  I only just discovered this last night so I've only run it once or twice but all I can think is "Testimo where have you been all my life?"  Anyway, I'm completely blown away by how awesome this is and I want to start using it more and running it at clients and presenting the reports to them but there's just one teensy problem.  You misspelled the word "Extreme" as "Extream".  I noticed your code is signed which is great but also means I can't just fix it myself without losing the signing and the least I can do to give back is to report this anyway.  I script quite a bit but I've still not really gotten familiar enough with github to feel comfortable doing a pull and commit myself.

Regardless this should be the easiest bug to squash ever.  All you need to do reproduce is run it with defaults in a domain which has an Extreme importance level result and in the resulting HTML report that pops open you'll see that Extreme is incorrectly spelled as Extream.  I'm unsure if this appears elsewhere as I've only just begun to play with this module.

![image](https://user-images.githubusercontent.com/67213346/109539193-a6f1c180-7a86-11eb-82f9-94a6afab180c.png)

**Comment by PrzemyslawKlys** [comment]
The fix is really simple - Just modify this:

https://github.com/EvotecIT/Testimo/blob/135128c9bbfb069844742eca3cc4a1784e22ac98/Private/RiskLevels.ps1#L12

Care to submit PR? I will release it today if you fix it :-)

**Comment by mojomojoman** [comment]
Actually it might be more common to use the word "Critical" for importance level.
Most common levels used in other things would probably be like:
Informational, Notice, Warning, Medium, High, Critical
Or some variation on those.

Umm, I'm a little embarassed to say I'm a complete and total git noob. I'll have to google how to do that.

**Comment by PrzemyslawKlys** [comment]
You can edit small issues like that from web interface. Here are the levels

```
$Script:Importance = @{
    0  = 'Informational'
    1  = 'Neglible)'
    2  = 'Very low'
    3  = 'Low'
    4  = 'Minor'
    5  = 'Moderate Low'
    6  = 'Moderate'
    7  = 'High'
    8  = 'Very High'
    9  = 'Signiciant'
    10 = 'Extream'
}
```

We also use for assesment

```
$Script:StatusTranslation = @{
    -1 = 'Skipped'
    0  = 'Informational' # #4D9F6F # Low risk
    1  = 'Good'
    2  = 'Low' # #507DC6 # General Risk
    3  = 'Elevated' # #998D16 # Significant Risk
    4  = 'High' # #7A5928 High Risk
    5  = 'Severe' # #D65742 Server Risk
}
```

And action types:

```
$Script:ActionType = @{
    0 = 'Informational'
    1 = 'Recommended'
    2 = 'Must Implement'
}
```

**Comment by PrzemyslawKlys** [comment]
Important & Actions are "informational". The TRUE coloring is based on Status Translation. This is actually new feature so not yet decided how this should work.

**Comment by mojomojoman** [comment]
Oh. NOW I find out I could have done it easily in the web GUI. Haha.  I was so heads down figuring out how to do this VS Code that I didnt read your comment.  Anyway, I think I successfully forked it and pushed to the fork and submitted the PR and in fact found several corrections to make.  Again, I'm a total noob here with git so double check everything but I think I did it right.  Thanks for making me learn a thing I should have known for a while probably.

**Comment by PrzemyslawKlys** [comment]
Thank you for https://github.com/EvotecIT/Testimo/pull/121

Are you ready or do you want to change something else?

**Comment by mojomojoman** [comment]
Go for it.  That file is at least all good now. Some project managers are asking me what i've been doing the last few hours so I gotta get back to my real job anyway. ;-)

**Comment by mojomojoman** [comment]
dumb question but I suppose this won't make it out to psgallery right away?  I mean can I just do an Update-Module later on the remote systems i'm working on and get the change?  I imagine these things run at a delay or you have to occasionally push a new release.

**Comment by PrzemyslawKlys** [comment]
It's already done. I've pblished changes already

**Comment by PrzemyslawKlys** [comment]
Generally, you can monitor GitHub for releases

![image](https://user-images.githubusercontent.com/15063294/109548992-a03a6d00-7acd-11eb-9495-4387e8920cbd.png)

When I publish to PSGallery, 3 seconds later publish to GitHub happens. Running `update-module testimo` gets new changes as required from PSGallery.  Using it ad-hoc shouldn't bring any problems, but when you do automation around Testimo - you may want to test changes before blindly updating. I do changes pretty frequently lately which means potential breaking changes for automation.
