### ISSUE TITLE
On version 0.70, I dont see -ReturnResults

### ISSUE THREAD

**Issue by Tpaquot** [EvotecIT/Testimo#130]
Hello, 

i like testimo tahnk you very much for having made this 
I don't see returnresults anylmore 
is this desired ? 

help Invoke-Testimo -Detailed

NAME
    Invoke-Testimo

SYNTAX
    Invoke-Testimo [[-Sources] <string[]>] [[-ExcludeSources] <string[]>] [[-ExcludeDomains] <string[]>]
    [[-ExcludeDomainControllers] <string[]>] [[-IncludeDomains] <string[]>] [[-IncludeDomainControllers] <string[]>]
    [[-ForestName] <string>] [[-Configuration] <Object>] [[-FilePath] <string>] [[-ExternalTests] <string[]>] [-PassThru]
    [-ShowErrors] [-ExtendedResults] [-ShowReport] [-HideHTML] [-HideSteps] [-AlwaysShowSteps] [-SkipRODC] [-Online]
    [<CommonParameters>]

PARAMETERS
    -AlwaysShowSteps

    -Configuration <Object>

    -ExcludeDomainControllers <string[]>

    -ExcludeDomains <string[]>

    -ExcludeSources <string[]>

    -ExtendedResults

    -ExternalTests <string[]>

    -FilePath <string>

    -ForestName <string>

    -HideHTML

    -HideSteps

    -IncludeDomainControllers <string[]>

    -IncludeDomains <string[]>

    -Online

    -PassThru

    -ShowErrors

    -ShowReport

    -SkipRODC

    -Sources <string[]>

    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https:/go.microsoft.com/fwlink/?LinkID=113216).

**Comment by PrzemyslawKlys** [comment]
I've renamed it to -Passhtru and left it as an alias `[alias('ReturnResults')][switch] $PassThru,`
