### ISSUE TITLE
DNSResolveExternal test reports failures on A records returned in the Authority and Additional sections

### ISSUE THREAD

**Issue by rmbolger** [EvotecIT/Testimo#132]
This issue is very similar to https://github.com/EvotecIT/ADEssentials/issues/17

The code that checks resolution against `testimo-check.evotec.xyz` fails to limit the results to A records in the Answer section. So there are a bunch of false failures in the test output for the NS records in the Authority section and the A records associated with those NS records in the Additional section.

https://github.com/EvotecIT/Testimo/blob/738b23f4aeefaae151857e003cf8b41f1e05e8e1/Private/SourcesDomainControllers/DNSResolveExternal.ps1#L7-L9

The code should be updated to only consider the A record values returned in the Answer section.

**Comment by PrzemyslawKlys** [comment]
Thank you for your PR. Really apppreciate it
