### ISSUE TITLE
Group Policy SysvolDC checking for non-existent property

### ISSUE THREAD

**Issue by jwmoss** [EvotecIT/Testimo#135]
While running this for the first time, I discovered an issue which may stem from `Get-GPOZaurrSysvol`.

In line 7 of [GroupPolicySysVolDC](https://github.com/EvotecIT/Testimo/blob/master/Private/SourcesDomainControllers/GroupPolicySYSVOLDC.ps1#L7), you're checking for SysvolStatus property:

```PowerShell
Get-GPOZaurrSysvol -IncludeDomains $Domain -IncludeDomainControllers $DomainController -VerifyDomainControllers | Where-Object { $_.SysvolStatus -ne 'Exists' -or $_.Status -ne 'Exists' }
```

But the property doesn't exist.

![image](https://user-images.githubusercontent.com/2729151/126352430-5faae2d4-4f67-479b-a918-f05eee7231ff.png)

Which returns a false negative

![image](https://user-images.githubusercontent.com/2729151/126352745-5927205a-88da-4709-8cf5-81a7c2a23371.png)

**Comment by PrzemyslawKlys** [comment]
Ye, it seems I've rewritten Get-GPOZaurrSysVol in GPOZaurr without updating Testimo. Thanks for noticing.

**Comment by jwmoss** [comment]
> Ye, it seems I've rewritten Get-GPOZaurrSysVol in GPOZaurr without updating Testimo. Thanks for noticing.

Sure thing!
