### ISSUE TITLE
Failure for several tests when using WinRM over HTTPS

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#136]
I have deployed WinRM over HTTPS for a client, and now Testimo fails several tests. Adding support would be great.

- Operating System
- Service Status
- RDP Security
- Disk Free
- Time Settings
- Network & Firewall status
- Roles & Features
- etc...

**Comment by PrzemyslawKlys** [comment]
Can you test available protocols that works? `Get-ComputerDisk -Protocol Wsman -ComputerName AD1` ?

**Comment by SUBnet192** [comment]
For WinRM over HTTPS to work, the connections (for example enter-pssession, needs to specify the FQDN and -UseSSL)

I tried the get-computerdisk and it fails.

From: Przemysław Kłys ***@***.***>
Date: Monday, July 26, 2021 at 3:31 PM
To: EvotecIT/Testimo ***@***.***>
Cc: Marc Bouchard ***@***.***>, Author ***@***.***>
Subject: Re: [EvotecIT/Testimo] Failure for several tests when using WinRM over HTTPS (#136)

Can you test available protocols that works? Get-ComputerDisk -Protocol Wsman -ComputerName AD1 ?

**Comment by PrzemyslawKlys** [comment]
Right, but we don't use enter-pssession :) It's going to be a pain.

**Comment by SUBnet192** [comment]
That was just an example 😉 WAC uses WinRM and retrieves all the appropriate data, there must be a way 😊

Thanks for taking the time to respond, I’ll try to investigate further later

From: Przemysław Kłys ***@***.***>
Date: Monday, July 26, 2021 at 3:43 PM
To: EvotecIT/Testimo ***@***.***>
Cc: Marc Bouchard ***@***.***>, Author ***@***.***>
Subject: Re: [EvotecIT/Testimo] Failure for several tests when using WinRM over HTTPS (#136)

Right, but we don't use enter-pssession :) It's going to be a pain.

**Comment by PrzemyslawKlys** [comment]
I mean - I am saying it's gonna be a pain for a simple reason - each cmdlet can either be just one query or multiple ones inside and each test is different. There are very few tests working the same way. We need a list of things that work and don't work using certain methods and then go one by one and see what works, and what doesn't work.

**Comment by SUBnet192** [comment]
***@***.***

What is the issue here?

Thanks,

Marc

**Comment by SUBnet192** [comment]
My configurations appear to be correct, yet I get this :

***@***.***

**Comment by PrzemyslawKlys** [comment]
I believe when you respond via email to a ticket GitHub scrubs away emails, hiding sensitive data.

**Comment by SUBnet192** [comment]
Ignore, as it's an unlikely scenario in the future
