### ISSUE TITLE
Unknown/unclear errors

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#137]
![image](https://user-images.githubusercontent.com/11916348/129959090-d6bc2064-7abf-4fd3-85b8-e877e522b9a2.png)

What is the Forest DHCP error when everything else is clean?

**Comment by SUBnet192** [comment]
Any insight into this?

**Comment by PrzemyslawKlys** [comment]
It means data was returned from Get-WinADDHCP. It's probably an error on my part. 

- https://github.com/EvotecIT/ADEssentials/blob/master/Public/Get-WinADDHCP.ps1

It needs fixing and be just informational.

**Comment by PrzemyslawKlys** [comment]
Actually, it's already informational in HTML 

![image](https://user-images.githubusercontent.com/15063294/136452660-cbfc1311-d052-4776-8455-bd53120ec860.png)

It's just that "console" output still operates in True/False mode only without taking into consideration what HTML shows.

**Comment by SUBnet192** [comment]
It showed as "bad" in console and html

Marc Bouchard
________________________________

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/136508366-cc49b857-80b5-4395-a4b2-5c9c76e0a9cc.png)

That's what I get? Was it red?

**Comment by SUBnet192** [comment]
It now shows "Data is available" in command line as well. Case closed :) Thanks!

![image](https://user-images.githubusercontent.com/11916348/143778360-8b34f935-5067-483b-9c63-51b19c70775b.png)
