### ISSUE TITLE
Incorrect values?

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#138]
![image](https://user-images.githubusercontent.com/11916348/129959165-4ba764a6-0960-46c0-91ad-5a44e9355996.png)

Permissions appear to be fine but are reported as wrong. Is it a case of wrong comparison values?

**Comment by PrzemyslawKlys** [comment]
are those not incorrect?

**Comment by SUBnet192** [comment]
Same as #144
