### ISSUE TITLE
Testimo failed run - Get-WinADForestDetails : Cannot index into a null array.

### ISSUE THREAD

**Issue by saliumaama** [EvotecIT/Testimo#139]
I'm having this error message when I run Invoke-Testimo. Not sure why. Is there anything I'm doing wrong ? Is Testimo supposed to be run ONLY on domain controllers ?

[i][Testimo] Version [Informative] [Current: 0.0.72]
[i][Testimo] Using configuration defaults [Informative] [No configuration provided by user]
Get-WinADForestDetails : Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Testimo\0.0.72\Testimo.psm1:6298 char:22

... stDetails = Get-WinADForestDetails -WarningVariable ForestWarning -Wa ...
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : InvalidOperation: (:) [Get-WinADForestDetails], RuntimeException
FullyQualifiedErrorId : NullArray,Get-WinADForestDetails
image

![image](https://user-images.githubusercontent.com/91435738/134823738-5007cc9e-efaa-47ab-ae84-aa77f96bdc87.png)

**Comment by saliumaama** [comment]
In response to the request "Please check: Get-ADForest, Get-ADDomain - does that work properly?"

Yes, both commands run successfully with no issues on the same Windows 10 that I run the Invoke-Testimo from.

**Comment by PrzemyslawKlys** [comment]
And when you run `Get-WinADForestDetails` do you get an error?

**Comment by saliumaama** [comment]
This is what I get. The domain shown is our child domain that longer exist. It was set up years ago only as a test. Is there a way I can force the Testimo to ignore that domain ?

![image](https://user-images.githubusercontent.com/91435738/134911266-725e74f8-1bec-483c-8d4a-807df763ac4d.png)

**Comment by PrzemyslawKlys** [comment]
I'll try to fix it, so it skips it automatically down domains... but - you should remove it a long time ago - as this is hugely affecting your AD.

**Comment by PrzemyslawKlys** [comment]
Install-Module PSSharedGoods -Force -Verbose

It should fix your issue. Please let me know

**Comment by saliumaama** [comment]
still getting some errors:

![image](https://user-images.githubusercontent.com/91435738/135703435-2b5e0ac3-0b99-451f-8a87-a2a6901ccedd.png)

**Comment by PrzemyslawKlys** [comment]
If you're doing it all in one session you need do Import-Module PSSharedGoods -Force first 

When you open up PowerShell and you have some modules installed they often pre-import themselves. So close PowerShell, retry Invoke-Testimo.

Also `Get-Module -list PSSharedGoods` because the not enough memory looks weird.

**Comment by saliumaama** [comment]
I closed /Open PS as you suggested and so far it appears to be running good. I believe the error I'm seeing are due to those dormant domains we talked about. Script is still as of this message

![image](https://user-images.githubusercontent.com/91435738/135716545-e00fafd3-cb9b-41f1-b4e4-8a503ca7dcd9.png)

**Comment by PrzemyslawKlys** [comment]
You should fix your issue first! It's critical for your domain.
