### ISSUE TITLE
Some tests report Fail but no reason why

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#143]
![image](https://user-images.githubusercontent.com/11916348/143610711-3e2bba1a-0b27-425c-9f1a-b91fd0e244eb.png)

![image](https://user-images.githubusercontent.com/11916348/143610722-46e258d2-d2e8-4198-a5fc-4fca1fea0a1a.png)

Built a new lab with 5 VMs (2 DC/DNS, 2 PKI (root/sub) and Mgmt server using Windows 2022, so this is all fresh, no legacy settings. DHCP is not installed on DCs, I installed one on the mgmt server just for the test. Both of these should pass, not fail.

**Comment by PrzemyslawKlys** [comment]
Can you provide the output of `Get-WinADDHCP` ?

**Comment by PrzemyslawKlys** [comment]
Those should fix it

**Comment by SUBnet192** [comment]
![image](https://user-images.githubusercontent.com/11916348/143770715-cd8aca45-ee12-4006-9f48-2e27eb89accb.png)

and

![image](https://user-images.githubusercontent.com/11916348/143770743-a8ee1122-b68d-4b3a-8af9-842187ebc7a5.png)
