### ISSUE TITLE
Odd values/errors - need explanation

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#144]
![image](https://user-images.githubusercontent.com/11916348/143625443-7d733235-c679-4267-aa58-731e6fece536.png)

New domain in a lab, fresh install of 2022. The share permissions are all OK, but the "share permissions value" are all erroring out. what is that and why?

**Comment by PrzemyslawKlys** [comment]
You should use HTML information to find out what it shows. New domains have some discrepancies when it comes to built-in Administrators. 

Or there is a bug but without more HTML output with details it's hard to say.

**Comment by PrzemyslawKlys** [comment]
You can run Invoke-GPOZaurr to see for yourself consistency of gpos for example will be broken. That Invoke-GPOZaurr -Type NetLogonPermissions should show you your problem too.

**Comment by SUBnet192** [comment]
Invoke-GPOZaurr -Type Netlogonpermissions returns nothing.
![image](https://user-images.githubusercontent.com/11916348/143770583-21a75086-40b0-443f-acb5-ae32c5dac031.png)

**Comment by SUBnet192** [comment]
The original error message indicates "expecting value Read, found value 2". I think the check is comparing the wrong values?

**Comment by PrzemyslawKlys** [comment]
Must be. I may have changed the output of the original cmdlet. Need to re-test it.

**Comment by PrzemyslawKlys** [comment]
What does this show: `Get-ComputerSMBSharePermissions -ComputerName ad1 -ShareName Netlogon,Sysvol` ?

![image](https://user-images.githubusercontent.com/15063294/143922154-5a3204e8-fc43-48f0-b91a-38be7717b79e.png)

That's for me

**Comment by SUBnet192** [comment]
![image](https://user-images.githubusercontent.com/11916348/143922344-598e6c63-2d36-46b8-8fe8-8d3790798c1e.png)

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/143923348-152db3a7-d724-4639-ae52-117a02badf13.png)

That is so weird :/

**Comment by SUBnet192** [comment]
![image](https://user-images.githubusercontent.com/11916348/143951105-befb97d5-5b79-4d8c-b724-609fee88133b.png)
I reapplied the default permissions to SYSVOL/Netlogon and all is fine now. Somehow one of the 2 BRAND NEW domain controllers in a BRAND NEW domain got borked... Oh well...

**Comment by PrzemyslawKlys** [comment]
Glad this got solved. That means the tool is working as expected ;-)

**Comment by GertVanderstukken** [comment]
Hmm, 

I seem to have the same problem on a brand new Windows 2022 Domain Controller.
Share permissions are correct, but it seems that the script is performing a count instead of a check towards the value in AccessRight.

![image](https://user-images.githubusercontent.com/53289938/210172276-b8b51819-8aa8-4ec1-af51-9648e846eb1e.png)

When I check the last printscreen from SUBnet192, I see that it is not checking against Read or Full anymore, but against a number???

**Comment by PrzemyslawKlys** [comment]
There is something wrong with this. I can replicate this but it shows up once every X number of times. I'll investigate.

**Comment by PrzemyslawKlys** [comment]
0.0.85 should fix this issue. I've reworked the cmdlet. The numbers were coming from Enums, and then we had some weird issue with Share command would return incomplete information. Hopefully now it's more bulletproof.

**Comment by GertVanderstukken** [comment]
Great.

I can confirm it's now working as expected.
Thanks!!!
