### ISSUE TITLE
Event Logs issue on new domain Windows 2022

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#146]
![image](https://user-images.githubusercontent.com/11916348/143879487-357c470f-c917-45c4-865e-c9e187ed2c0d.png)

All logs test fail.

**Comment by PrzemyslawKlys** [comment]
Probably WINRM accessibility. Make sure you have proper ports open, and connectivity is there.

**Comment by SUBnet192** [comment]
Remote Event Log management firewall rule was missing. thanks :)
