### ISSUE TITLE
Nitpicking - status display

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#147]
![image](https://user-images.githubusercontent.com/11916348/143899532-c5f87dbf-1895-42ae-b589-6656ecd8194e.png)

I would suggest removing the period on the status for "No data returned" and "Data is available". Just looks odd. Definitely a preference, not a critical issue.

**Comment by SUBnet192** [comment]
Wrong strings fixed - commits are not the same as what I proposed.

**Comment by PrzemyslawKlys** [comment]
Shouldn't it be fixed for everything?

**Comment by PrzemyslawKlys** [comment]
It will take a moment as I'm testing more changes

![image](https://user-images.githubusercontent.com/15063294/143907006-564793f0-c970-442d-a436-9573b4447408.png)
