### ISSUE TITLE
Orphaned/Empty OUs can be normal - shouldn't be flagged as failed.

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#152]
For example, I build an "archive" OU for each client, where they move objects that are disabled/to be deleted etc... so at times it's empty. I wouldn't mark orphaned OUs as failed. Maybe another status (recommended/warning?)

**Comment by PrzemyslawKlys** [comment]
All those that says True/False - Pass/Fail are old versions

New version:

![image](https://user-images.githubusercontent.com/15063294/143924043-408a7b0e-7308-4312-9ec4-c7a252990340.png)

Old version:

![image](https://user-images.githubusercontent.com/15063294/143924119-53215a3b-63cc-46b0-982d-30dba2dac2e3.png)

All the old tests needs to be reviewed and updated and have proper Importance and action type. 

![image](https://user-images.githubusercontent.com/15063294/143924188-5245164f-974e-42f5-87cb-897bf363b8cc.png)

![image](https://user-images.githubusercontent.com/15063294/143924212-4c80b56f-026d-42bd-a9a2-2f165dd87e26.png)

But even going thru all tests and fixing that is pain so I only do that when I have time and I explicitly need this to be fixed.
