### ISSUE TITLE
3 issues left

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#153]
![image](https://user-images.githubusercontent.com/11916348/143952643-6e89b9c7-42c3-4c0b-9c9b-75d33d35ad4d.png)

GPO Permission Consistency is fine (according to the GPMC sync test)
Files on SYSVOL are not Orphaned (should be fine as well, I don't see anything orphaned)
Netlogon Owner: fails, no idea why.

Everything else is now green (in my test lab) - I'm documenting what needs to be fixed for each issue and automating the resolution of these issues. At the same time, I'm going through and helping you find issues with code. Is there a better way to submit questions than submitting an Issue? I know I could ask you on Reddit as well but at least here it's centralized.

**Comment by PrzemyslawKlys** [comment]
Use:

1. Invoke-GPOZaurr -Type GPOConsistency - you will see it's not consistent. Default deployed forest starts inconsistent :) and GPMC Test - oh well
2. To be honest just run Invoke-GPOZaurr without anything and you will see 

For both 2 nd 3 I need more data to be able to tell if there's something wrong. Probably from GPOZaurr, not testimo, as those commands take input from GPOZaurr.

**Comment by SUBnet192** [comment]
Running GPOZaurr by itself, will see what I get. Everything was fine last time I checked...

1. GPO Consistency says every single GPO isn't consistent. Consistent with what exactly? :)
2. Netlogon owners and permissions is blank

![image](https://user-images.githubusercontent.com/11916348/143954603-2f061024-c61e-4334-9851-faac71309b65.png)

**Comment by PrzemyslawKlys** [comment]
I guess you have 0 files - and hence the error. I need to update the test. I expected at least 1 file.

For GPOCosistency - the consistency is checked between AD and SYSVOL. They are supposed to match. Same goes for consistency for files inside the GPO on sysvol - it should match with top-level permissions.

**Comment by SUBnet192** [comment]
Oh! Ok, I'll create something in Netlogon and rerun. That would make sense ;) And yes you'll have cases where net logon is empty... Rare but happens ;)

Permissions are fine for the Consistency, I guess there's something between AD and SYSVOL. I'll investigate and report. Thank you!
