### ISSUE TITLE
Typo in SecurityComputers.ps1

### ISSUE THREAD

**Issue by shivtorov** [EvotecIT/Testimo#156]
Line 116 should say `Domain Computers or Domain Controllers or Read-Only Domain Controllers` instead of `Domain Users`

https://github.com/EvotecIT/Testimo/blob/8f13cd3b827866315c2d2f16f5cf954097f8c117/Private/SourcesDomain/SecurityComputers.ps1#L114-L132

**Comment by PrzemyslawKlys** [comment]
Thank you. You could always fix it yourself :-) It's quite easy
