### ISSUE TITLE
Report Ldaps AD LDS

### ISSUE THREAD

**Issue by amroth3003** [EvotecIT/Testimo#166]
Hello, is there any way to perform the Invoke-Testimo as ldap test to the AD LDS servers

**Comment by PrzemyslawKlys** [comment]
I never used AD LDS server but maybe: https://evotec.xyz/monitoring-ldaps-connectivity-certificate-with-powershell/

```powershell
Test-LDAP -VerifyCertificate -ComputerName YourADLDSServer | Format-Table -AutoSize
```
