### ISSUE TITLE
Add target forest parameter to specify AD forest to check

### ISSUE THREAD

**Issue by red-erik** [EvotecIT/Testimo#167]
Hello,
thank you for sharing your code.
We use ESAE (Red Forest) to manage prod ADDS so when I Invoke Testimo it's is executed in my user session for my account from RED forest and it analyze Red forest only and not production one.
Is there a way to specify the target Forest ?
Thank you in advance,
Red.

**Comment by PrzemyslawKlys** [comment]
You already can do that.

![image](https://user-images.githubusercontent.com/15063294/180227142-892bbf74-b29b-4387-89e6-847a114e89d9.png)

Not everything will work, but at least it's a start. Then you would need to prepare a list of what works, what doesn't and then one by one test would need to be fixed to support another forest.
