### ISSUE TITLE
Get-TestimoConfiguration fails after update to 0.0.83

### ISSUE THREAD

**Issue by LemurTech** [EvotecIT/Testimo#171]
Hi! On two different machines I am unable to load the configuration for modification using Get-TestimoConfiguration. This is on 0.0.83. The error is "Cannot index into a null array". "invoke-testimo" works, as long as any custom configuration is not passed. 

PS C:\Windows\system32> import-module Testimo -force
PS C:\Windows\system32> **Get-TestimoConfiguration**
Get-TestimoConfiguration : Cannot index into a null array.
At line:1 char:1
+ Get-TestimoConfiguration
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-TestimoConfiguration], RuntimeException
    + FullyQualifiedErrorId : NullArray,Get-TestimoConfiguration

PS C:\Windows\system32> **invoke-testimo**
[i][Testimo] Version [Informative] [Current/Latest: 0.0.83 at 07/29/2022 03:53:41]
[i][Testimo] Using configuration defaults [Informative] [No configuration provided by user]
[i][Testimo] Following sources will be used [Valid Sources] [ForestBackup, ForestDHCP, ForestReplication, ForestReplicat
ionStatus, ForestOptionalFeatures, ForestSites, ForestSiteLinks, ForestSiteLinksConnections, ForestRoles, ForestRootKDS,
 ForestSubnets, ForestOrphanedAdmins, ForestTombstoneLifetime, ForestTrusts, ForestConfigurationPartitionOwners, ForestC
onfigurationPartitionOwnersContainers, ForestDuplicateSPN, ForestVulnerableSchemaClass, DomainLDAP, DomainMachineQuota,

**Comment by PrzemyslawKlys** [comment]
![FacepalmReallyGIF](https://user-images.githubusercontent.com/15063294/198353097-d685e931-7a88-4eb9-81b9-6984f10f17c9.gif)

**Comment by LemurTech** [comment]
It's like having Monday twice in one week!

**Comment by LemurTech** [comment]
Understood. I appreciate the update, and all your stellar work. You've helped me do things faster and better than I could have hoped for otherwise. You're an unsung hero! Now if only I could pronounce your name... :)

**Comment by PrzemyslawKlys** [comment]
Przemek (Shemek) as most people call me.

**Comment by LemurTech** [comment]
You, sir, are a Gentleman and a Scholar! Many thanks!
