### ISSUE TITLE
Multiple errors with missing cmdlets

### ISSUE THREAD

**Issue by mnooseman** [EvotecIT/Testimo#173]
I've copied Testimo and it's dependencies over to a domain controller that's disconnected from the internet.  All required modules should be loaded but I still receive many error messages like the following:

      [t][Forest] Forest Replication [Severe] [The term 'Get-WinADForestReplication' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.]

Many of the tests respond with "Input data not provided. Failing test."

This is on a Windows Server 2022 domain controller.

**Comment by PrzemyslawKlys** [comment]
1. Where did you put the modules?
2. How did you load them?
3. What modules you actually put there?

**Comment by mnooseman** [comment]
Hi - Apologies for the delay.

I used your script to pull a portable version of Testimo first, and then I tried manually the second time.  Modules that were loaded in both cases are as follows:

ADEssentials
GPOZaurr
PSEventViewer
PSSharedGoods
PSWinDocumentation.DNS
PSWriteHTML
Testimo

When done through your portable creation script, they were loaded via the `Testimo.ps1` file that gets generated.

When done manually, I used `Import-Module` and imported using the same order that your portable creation script put out.

**Comment by PrzemyslawKlys** [comment]
ok, the portable script doesn't work properly due to some internal changes. I need to fix it. 

Just do:
- `Save-Module Testimo -Path XXX` on your workstation into some folder
- Once having all modules copy them onto DC into `C:\Program Files\WindowsPowerShell\Modules` 

After that just open powershell and it will work. You do know that you can run Testimo from outside of DC itself right?

**Comment by mnooseman** [comment]
Seems to work for the most part, but still fails out the Get-WinADDHCP cmdlets from ADEssentials.  Cmdlet not found.

**Comment by PrzemyslawKlys** [comment]
You need to install RSAT for DHCP. So just add a DHCP feature.

**Comment by mnooseman** [comment]
DHCP was installed as a role on that DC (bad idea, I know - we just took this environment over through an acquisition)

I'll double check that the DHCP powershell stuff is there.
