### ISSUE TITLE
powershell crash

### ISSUE THREAD

**Issue by shosho-san** [EvotecIT/Testimo#174]
Hi,
I have a reproductible powershell crash issue when i launch invoke-Testimo -Source 'ForestTrusts'
![image](https://user-images.githubusercontent.com/17947358/213491587-0b6ded39-dd82-4dc4-bf97-cbdc8b7495b5.png)

ps:i have a bi-directional trust with another forest in place.
it's failed on a windows server 2019 french with powershell 5.1 (member server), not tested on other server

regards

**Comment by PrzemyslawKlys** [comment]
I'm sorry, but I am not sure how I can help. to me, it seems like something related to PowerShell and specifics of your machine, not my module problem or something I can address.
