### ISSUE TITLE
Cannot install using Install-Module; Another method to run and install?

### ISSUE THREAD

**Issue by riahc3** [EvotecIT/Testimo#178]
Hello

The server Im on (2016) for some reason doesnt want to install Testimo using install-module (nuget errors, etc)

Is there a way to run this offline? I tried to download the entire repository but it gives me further errors on cmdlets and functions missing.

Thank you

**Comment by PrzemyslawKlys** [comment]
`Save-Module Testimo -Path "C:\Temp"` on your own machine with internet access. Once it downloads locally go to that C:\Temp and copy all the modules that it downloads (it will be like 7 of them) to `C:\Program Files\WindowsPowerShell\Modules` to make modules available on that server. Remember that Testimo doesn't require server, nor has to be run on DC.

**Comment by riahc3** [comment]
Thank you.

This should be added to the documentation

**Comment by PrzemyslawKlys** [comment]
feel free to make PR. This is standard for any PowerShell module tho
