### ISSUE TITLE
Issues in 0.0.86 release

### ISSUE THREAD

**Issue by robertRuncak** [EvotecIT/Testimo#181]
Invoke-Testimo has some issues to collect data. 0.0.85 release works fine.
[output.txt](https://github.com/EvotecIT/Testimo/files/13890821/output.txt)

**Comment by PrzemyslawKlys** [comment]
That's not really helpful. Please provide more information.

**Comment by PrzemyslawKlys** [comment]
Install-module pssharedgoods -force -verbose and it will work again

**Comment by robertRuncak** [comment]
That works. Is this a feature?

**Comment by PrzemyslawKlys** [comment]
No. Dependency issue on merge.
