### ISSUE TITLE
DCSMBSharesPermissions not working properly on Non-English systems

### ISSUE THREAD

**Issue by diecknet** [EvotecIT/Testimo#190]
I noticed that the `DCSMBSharesPermissions` test is not working properly on a German system.
Looks like the names are hardcoded.

For example: https://github.com/EvotecIT/Testimo/blob/a358a778f9c8b136cd52960a81e35def6b5629be/Private/SourcesDomainControllers/SMBSharesPermissions.ps1#L45
But it's multiple times in that file.

I can propose a PR soon to fix that, but don't have time right now

**Comment by PrzemyslawKlys** [comment]
Maybe there is better way to do it then hardcode other languages

**Comment by SamErde** [comment]
Reference well-known SIDs?

**Comment by PrzemyslawKlys** [comment]
This requires looking at different source:

![image](https://github.com/user-attachments/assets/043a3da7-81ad-4704-b7fc-ed355a18333e)

As the one I have

![image](https://github.com/user-attachments/assets/0717462c-acd5-4018-aea5-8b29b8ffd395)

Is all about AccoutnName, probably would need to use COnvertIdentity

![image](https://github.com/user-attachments/assets/5666e3c9-ff8f-43e4-bc62-0b3d3cdfc869)

And make sure the SID is there and then compare for SID.

**Comment by diecknet** [comment]
There are some .NET methods we can use. I used them in the past. Here are some examples: https://github.com/diecknet/diecknet-scripts/blob/main/Snips/Get-LocalizedNTAuthority.ps1

**Comment by PrzemyslawKlys** [comment]
Thats what convert-identity does but a bit more

**Comment by PrzemyslawKlys** [comment]
Convert-Identity just can convert pretty much everything it can into SID/Name and type/domain name including special accounts

![image](https://github.com/user-attachments/assets/45318a2d-fadc-4e3f-b756-524b5b10134d)

![image](https://github.com/user-attachments/assets/9be9cbed-e4c2-47e1-b052-102c98326c6d)

**Comment by PrzemyslawKlys** [comment]
PSSharedGoods

**Comment by diecknet** [comment]
I see a few possible options:
a) Change `Get-ComputerSMBSharePermissions` in PSSharedGoods to return internationalized AccountNames instead of localized.
b) Change the `DCSMBSharesPermissions` test in Testimo to work with localized names by well known SIDs.

Option `a` *could* improve future compatibility with other tests/scripts. Option `b` on the other hand, keeps the localized names in the report. That could be easier to understand for some people.

**Comment by PrzemyslawKlys** [comment]
Ye, change/improve PSSharedGoods and then modify tests to match it.

**Comment by PrzemyslawKlys** [comment]
Here's a quick fix:
![image](https://github.com/user-attachments/assets/b8abdb59-30ee-4e59-8bda-120abdfa4eb3)

**Comment by PrzemyslawKlys** [comment]
![image](https://github.com/user-attachments/assets/2df68c52-7f37-4aac-bbdc-7c0729b78ea5)
![image](https://github.com/user-attachments/assets/31834f7d-13d2-459f-ad3d-85b889f336b8)

**Comment by PrzemyslawKlys** [comment]
And woila all done :-)

**Comment by diecknet** [comment]
Awesome! Thank you @PrzemyslawKlys :)
