### ISSUE TITLE
All of my GPOs show False under "Optimized"

### ISSUE THREAD

**Issue by paulr24** [EvotecIT/Testimo#192]
All of my GPOs show False under "Optimized." I assume that is abnormal... How can I find what about them specifically needs to be optimized?

**Comment by PrzemyslawKlys** [comment]
You can run GPOZaurr to understand more:
- https://evotec.xyz/the-only-command-you-will-ever-need-to-understand-and-fix-your-group-policies-gpo/

Not optimized means that GPO targets for example User Section but also has Computer Section Enabled. It's not super important, but it will give you few milliseconds on GPO processing. You can ignore it if you don't fancy fixing it, not a big deal unless there are some performance issues.

**Comment by paulr24** [comment]
> You can run GPOZaurr to understand more:
> 
>     * https://evotec.xyz/the-only-command-you-will-ever-need-to-understand-and-fix-your-group-policies-gpo/
> 
> 
> Not optimized means that GPO targets for example User Section but also has Computer Section Enabled. It's not super important, but it will give you few milliseconds on GPO processing. You can ignore it if you don't fancy fixing it, not a big deal unless there are some performance issues.

Got it, thank you for the explanation!
