### ISSUE TITLE
Loading configuration from a path to a json doesn't work

### ISSUE THREAD

**Issue by alexsmid** [EvotecIT/Testimo#30]
When loading a configuration file, as a path, it will always give the same error:
`> Invoke-Testimo -Configuration "C:\Temp\testmio.json"
[t][Forest] Loading configuratio failed. Skipping. [Informative] [Not JSON/Hashtable or syntax is incorrect.]
[t][Forest] Using configuration provided by user [Informative] [Configuration loaded from ]`

This is because in the "Import-TestimoConfiguration" function you reference to "$Object" two times where it should be "$Configuration":

`} elseif ($Object -is [string]) {
            if (Test-Path -LiteralPath $Object) {
                $Option = 'File'
                $FileContent = Get-Content -LiteralPath $Configuration
            }`

Should be:

`} elseif ($Configuration-is [string]) {
            if (Test-Path -LiteralPath $Configuration) {
                $Option = 'File'
                $FileContent = Get-Content -LiteralPath $Configuration
            }`

**Comment by PrzemyslawKlys** [comment]
Thank you for noticing. Hope you can make PR's in future improving Testimo :-) I've fixed it now.

**Comment by PrzemyslawKlys** [comment]
Published new version. Please test.
