### ISSUE TITLE
Get-TimeSetttings ignore Policies Entries

### ISSUE THREAD

**Issue by ruddj** [EvotecIT/Testimo#41]
Good Day,
 First great job on the tool. It helped us identify some things we need to look at in our environment.
2 Comments about the Time settings check.

The Get-TimeSetttings command seems to ignore entries in HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\W32time 
We use a group policy with WMI filter for PDC to configure our NTP time server, but report does not pick up the changed values.

2nd is the TimeSynchronizationExternal check always checks pool.ntp.org which may be blocked by environments that don't allow internet access from their DCs. This is probably a more local config issue.

**Comment by PrzemyslawKlys** [comment]
Ok, both problems should be now fixed. Hope you can test when a new version gets released.

**Comment by ruddj** [comment]
Thank you. I will update and test when next release is pushed to Powershell Gallery.
