### ISSUE TITLE
Please add detection of missing "Net Cease" settings

### ISSUE THREAD

**Issue by rafalfitt** [EvotecIT/Testimo#71]
https://gallery.technet.microsoft.com/Net-Cease-Blocking-Net-1e8dcb5b

**Comment by PrzemyslawKlys** [comment]
Thanks for reporting. Appreciate it. Would you like to try and add it yourself?

**Comment by PrzemyslawKlys** [comment]
Probably modification of https://github.com/EvotecIT/Testimo/blob/master/Private/SourcesDomainControllers/LanManServer.ps1

where you just need to do 2 queries into the registry, rather than one and then ask for a specific value.

**Comment by PrzemyslawKlys** [comment]
I see it also requires ACL check for Authenticated Users.

**Comment by PrzemyslawKlys** [comment]
Added
