### ISSUE TITLE
Email report

### ISSUE THREAD

**Issue by ysteve1** [EvotecIT/Testimo#75]
was trying to figure out a way to email the -showreport html page.
I tried the -Email switch but I guess that one is not ready yet, and when I tried with Emailimo I just got the basic table output.

Is there an option to email the -showreport output?

**Comment by PrzemyslawKlys** [comment]
You can use Emailimo to send an attachment. Simply use EmailAttachment command within emailimo and point it to saved report. The email switch will be added, just not yet ready.

**Comment by ysteve1** [comment]
ok, so i will need to input a filepath with the -showreport, I assume that would be the -reportpath switch, then when invoking emailimo i would use emailattachment with the path and report name that I used for the -reportpath switch.
thanks

**Comment by PrzemyslawKlys** [comment]
Yes. Something like that. This is temporary until all this is bundled up as built-in functionality.

**Comment by PrzemyslawKlys** [comment]
There's nothing needed for you to do. Emailimo/PSWriteHTML don't have configs.

**Comment by ysteve1** [comment]
I was able to use the emailattachment along with the -reportpath switch to get the showreport to email.
Thanks for the assistance and great scripts
