### ISSUE TITLE
Unable to send the  html summary report to email

### ISSUE THREAD

**Issue by johnAit** [EvotecIT/Testimo#77]
This is one great module! I'm having trouble to send the summary report to email. I already follow the guide on Testimo - Sending summary to email and nothing happens.

I have a internal smtp that i use for others automated reports but this one dosen't work.
Currently ia use the following confg for the other reports
```powershell
$EmailSubject = " "
$smtphost = "" 
$from = "" 
$EmailTo = ""
```
There's any advice or i'm missing somenthing?  Its mandatory to use this configiration?
```powershell
Email {
    EmailHeader {
        EmailFrom -Address 'myemail@evotec.pl'
        EmailTo -Addresses "otheremail@evotec.pl"
        EmailServer -Server 'smtp.office365' -UserName 'myemail@evotec.pl' -Password 'C:\Support\Important\Password-Evotec.txt' -PasswordAsSecure -PasswordFromFile -Port 587 -SSL
        EmailOptions -Priority High -DeliveryNotifications Never
        EmailSubject -Subject '[Reporting Evotec] Summary of Active Directory Tests'

}
```

**Comment by PrzemyslawKlys** [comment]
If you have internal server that works without login/password you need to skip username/password. Most likely in such a case, the port is also 25 not 587.

**Comment by johnAit** [comment]
Excuse my ignorance! to skip these options i have to let these fields empty?

**Comment by PrzemyslawKlys** [comment]
```powershell
Email {
    EmailHeader {
        EmailFrom -Address 'myemail@evotec.pl'
        EmailTo -Addresses "otheremail@evotec.pl"
        EmailServer -Server 'smtp.office365' -Port 587 -SSL
        EmailOptions -Priority High -DeliveryNotifications Never
        EmailSubject -Subject '[Reporting Evotec] Summary of Active Directory Tests'
}
```

Just remove the parameter and it's value.

**Comment by johnAit** [comment]
Got it ! i will try again and let you know!!  Thanks a bunch for the quaick reply!

**Comment by johnAit** [comment]
Hi! PrzemyslawKlys!

Thanks for the suggestions! I was able get the e-mail function to work.
