### ISSUE TITLE
Unable to Specify ConfigurationFile

### ISSUE THREAD

**Issue by ERAustin** [EvotecIT/Testimo#82]
Per the documentation here (https://evotec.xyz/what-do-we-say-to-health-checking-active-directory/) I ran the following:

`Get-TestimoConfiguration -FilePath "C:\Scripts\Testimo\TestimoConfiguration.json"`

I edit the json file in Notepad ++ and save it.  Then I run

`$ConfigurationFile = "C:\Scripts\Testimo\TestimoConfiguration.json"
$TestResults = Invoke-Testimo -ReturnResults  -ExtendedResults -Sources $Sources -Configuration $ConfigurationFile`

and I receive this output:

![image](https://user-images.githubusercontent.com/39779735/73029613-1b265400-3df5-11ea-842d-4aee458603ca.png)

**Comment by PrzemyslawKlys** [comment]
```powershell
Update-Module Testimo
```

Sorry about that. I've mistyped and instead of Hashtable used Scriptblock.

**Comment by ERAustin** [comment]
Thanks for the reply.  I've updated to version 0.0.31 and issue remains  :/

![image](https://user-images.githubusercontent.com/39779735/73032054-2aa89b80-3dfb-11ea-9a91-9a0ba7df1a47.png)

**Comment by PrzemyslawKlys** [comment]
Try to regenerate json and try it please. If it works than make changes.

**Comment by ERAustin** [comment]
So interestingly enough I recreated the file and copy/pasted my configuration and that didn't work.  I recreated the JSON again from scratch and imported with no changes and it worked.  I'll work on recreating this.  It appears to be working correctly now.  Thanks!

**Comment by PrzemyslawKlys** [comment]
Its related to one section in config. You can just fix that and it should work. Check the fix I did. Or simply rework it. Sorry

**Comment by PrzemyslawKlys** [comment]
I’ll add some checks for future proofing.
