### ISSUE TITLE
Test "Group Policy SYSVOL Verification" references invalid option for Get-WinADGPOSysvolFolders

### ISSUE THREAD

**Issue by pmormr** [EvotecIT/Testimo#83]
In testimo.psm1

Test "Group Policy SYSVOL Verification" is failing, unable to find reference to "ComputerName".

Looks like it was intended to be "DomainControllers", not "ComputerName"

Get-WinADGPOSysvolFolders -Domain $Domain -DomainControllers $DomainController | Where-Object { $_.SysvolStatus -ne 'Exists' }

Seems to work as designed.

**Comment by pmormr** [comment]
Code snippet above was around line 1322 in testimo.psm1

**Comment by PrzemyslawKlys** [comment]
Update-module Testimo

It should be fixed. I've reworked commands from the ADEssentials module last week and forgot I have to release/recheck Testimo. It's part of a larger update to Testimo where you will be able to really ignore servers/domains. Right now excluding / including servers in testimo is crippled. In new version, it will be much easier.
