### ISSUE TITLE
Test "Group Policy Legacy ADM Files" includes non-legacy files when testing

### ISSUE THREAD

**Issue by pmormr** [EvotecIT/Testimo#84]
Test "Group Policy Legacy ADM Files"

The filter switch used for the test seems to include files with four character extensions (admx, adml) when searching. Using include instead of filter gets the intended result. It's like there's an implicit star on the end of it when you're using filter (e.g. \*.adm\*) judging from my tinkering just now.

Testimo.psm1 line 272

Get-ChildItem -Path "\\\\$Domain\\SYSVOL\\$Domain\\policies" -ErrorAction Stop -Recurse -Include '*.adm' | Select-Object Name, FullName, CreationTime, LastWriteTime, Attributes

**Comment by PrzemyslawKlys** [comment]
Would you be able to provide PR for this? I mean I can fix issues myself but the more people do it, the better Testimo can get.

**Comment by PrzemyslawKlys** [comment]
The affected line is here:

https://github.com/EvotecIT/Testimo/blob/dc83535e517448967f94046c6648472a1d0277af/Private/SourcesDomain/GroupPolicyADM.ps1#L7-L8

**Comment by pmormr** [comment]
Sure... I think I have it all figured out.

https://github.com/EvotecIT/Testimo/pull/85

**Comment by PrzemyslawKlys** [comment]
Tnx, tested and you're indeed right. Not sure why I assumed it works with filter :/

**Comment by PrzemyslawKlys** [comment]
Released new version.
