### ISSUE TITLE
Guest user is not part of Domain Users group

### ISSUE THREAD

**Issue by itpro-tips** [EvotecIT/Testimo#88]
The 'Primary Group shouldn't be changed from default Domain Users' test always fails.

The reason is **guest** user has, by default, PrimaryGroupID=514 (GROUP_RID_GUEST) and not 513.
Maybe you had a good reason to not excluded the guest user of this test ?

If not, exclusion can be made with SID to be independant of AD language _S-1-5-21<domain>-501_

**Comment by PrzemyslawKlys** [comment]
I fixed this yesterday

https://github.com/EvotecIT/Testimo/blob/2790438f30ab91bcc0fb3d453cc5d47a4597bb6e/Private/SourcesDomain/SecurityUsers.ps1#L25

It wasn't committed as I started adding support for different forests. It should be eithe Domain Users or Domain Guests (I guess only for 1 account).

**Comment by PrzemyslawKlys** [comment]
But maybe it's just better to exclude guest user and not whole SID.
