### ISSUE TITLE
Trust Availability section

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#95]
Tests are failing if there are no existing trust relationships. Should pass or have a statuts like "not required" when not applicable.

 [i][ad.subnet192.com] Trust Availability [Informative]
         [t][ad.subnet192.com] Trust Availability [Fail] [No data available.]
         [t][ad.subnet192.com] Trust status verification [Fail] [Input data not provided. Failing test.]
         [t][ad.subnet192.com] Trust unconstrained TGTDelegation [Fail] [Input data not provided. Failing test.]

**Comment by PrzemyslawKlys** [comment]
Related: https://github.com/EvotecIT/Testimo/issues/64
