### ISSUE TITLE
Non-English language errors

### ISSUE THREAD

**Issue by SUBnet192** [EvotecIT/Testimo#97]
I assume this is due to the apostrophe in the group name. 

   [i][Forest] Orphaned Administrative Objects (AdminCount) [Informative] [Erreur lors de l’analyse de la requête : « Member -RecursiveMatch '**CN=Administrateurs de l'entreprise,CN=
Builtin,DC=excellence,DC=local**' » Message d’erreur : « syntax error » à la position : « 49 ».]

**Comment by PrzemyslawKlys** [comment]
Interesting. Will have to investigate.

**Comment by SUBnet192** [comment]
Replaced the ' ' with a back-tick to fix the issue.
$Group = Get-ADGroup -Filter "Member -RecursiveMatch `$DistinguishedName"
